name: 15 SCA

on:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: read

jobs:
  sca-dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}        
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high
          vulnerability-check: true
          head_ref: ${GITHUB_REF##*/} 
          base_ref: ${GITHUB_REF##*/} 
